export const GREEN_RESULTS = ['HIT GREEN', 'MISS GREEN', 'IN THE HOLE', 'PENALTY'];
export const FAIRWAY_RESULTS = ['HIT FAIRWAY', 'MISS FAIRWAY', 'HIT GREEN', 'MISS GREEN', 'IN THE HOLE', 'PENALTY'];
